### ISSUE TITLE
Save media as/now won't download gif

### ISSUE THREAD

**Issue by grssam** [marklieberman/foxygestures#42] opened 2017-08-29 15:54 UTC
If I run the gesture on a gif image, the download get initiated but always fails. Even retrying manually from download panel fails.

Example page : http://clamiral.tumblr.com/post/155735734176

**Comment by marklieberman** [comment] 2017-08-29 21:33
It's working fine for me. It might be on your end. Right click on the failed download and select "Copy Download Link" and paste it here please.

**Comment by grssam** [comment] 2017-08-29 21:40
right click -> copy image location - http://68.media.tumblr.com/82f7bbc1d06fcdbf1fd60cc2e8ced61a/tumblr_ojn0icZO9U1tai552o1_400.gif

failed download -> right click -> Copy download link - http://68.media.tumblr.com/82f7bbc1d06fcdbf1fd60cc2e8ced61a/tumblr_ojn0icZO9U1tai552o1_400.gif

PS : I am able to download using the normal right click -> save image as...

**Comment by marklieberman** [comment] 2017-08-29 21:52
I've tried it using release, developer, and nightly editions. It downloads fine using Save Media Now and Save Media As commands. The URL on the download is the correct one, so it means Foxy Gestures is calling the download API with the correct image source. Any issue with the download is unlikely to be from Foxy Gestures. Can you reproduce this on any other page or website?

**Comment by grssam** [comment] 2017-08-29 22:15
Looks like a tumblr only thing. I can download just fine from https://giphy.com/gifs/studiosoriginals-samantha-maurer-d3JIvDICfCu8jgaI or some other site.. weird.

I see the following exceptions in Browser Console:

```
Unchecked lastError value: Error: Frame not found, or missing host permission  ExtensionCommon.jsm:407
Error: WebExtension context not found! ExtensionParent.jsm:821:13
NS_ERROR_NOT_AVAILABLE: Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIChannel.contentType]  DownloadCore.jsm:1982
```

**Comment by grssam** [comment] 2017-08-29 22:15
(similar exceptions do not come on any other non-tumblr site.)

**Comment by marklieberman** [comment] 2017-08-29 22:28
I'm not seeing that error in my browsers when I have the GIF from tumblr.

That error is calling out `[nsIChannel.contentType]`. I guess it doesn't like the value it is seeing? Do you have any other addons that intercept web requests? There a good chance you've encountered a bug with Firefox as well, since that error is coming from inside Firefox code.

**Comment by grssam** [comment] 2017-08-29 22:29
I barely have any web extension based addons. But I can debug this using Browser Debugger later tomorrow.

**Comment by marklieberman** [comment] 2017-09-14 18:04
@grssam I'm going to close this issue. I will re-open if you discover any pertinent information.

**Closed by marklieberman** 2017-09-14 18:04 UTC
