### ISSUE TITLE
Xenforo text editor doesn't work when foxygestures is active

### ISSUE THREAD

**Issue by Lurtzae** [marklieberman/foxygestures#13] opened 2017-06-07 17:58 UTC
Since Nightly from June 5th, the text editor of Xenforo discussion boards doesn't load when foxygestures is activated. It loads however if DevTools are open. 
When it's not loading the console throws the following TypeError error: 'this.$editor[0] is undefined'. 

Foxygestures version 1.02 as distributed on AMO.

**Comment by marklieberman** [comment] 2017-06-07 18:06
Can you provide more information? The URL of the Xenforo discussion boards? The stack trace from that error?

The behavior changing with devtools is very strange. I have a hard time believing FoxyGestures is responsible.

**Comment by Lurtzae** [comment] 2017-06-07 18:10
You're right, I think it's something to do with Firefox, not Foxygestures. Tried SmartupGestures and it shows the same behaviour. 

Mouse Gesture Events are working though: https://addons.mozilla.org/en-US/firefox/addon/mouse-gestures/

I have opened a ticket in Bugzilla, but no resonance there until now. 

For me it shows on: 
www.android-hilfe.de/
www.gamestar.de/xenforo/

**Comment by Lurtzae** [comment] 2017-06-08 18:54
I did a bisection today and got the following ticket: https://bugzilla.mozilla.org/show_bug.cgi?id=1368152

Do you see a connection there?

**Comment by marklieberman** [comment] 2017-06-08 19:32
I'm not doing anything like that. All my uses of the WE API are very straightforward. FoxyGestures is very event driven. Aside from hooking into mouse DOM events it doesn't interact with the page in the tab much. That is why I find it difficult to believe that simply being installed is enough to break a website. When I have some time I will sign up one of those forums and check a bit more.

**Comment by Lurtzae** [comment] 2017-06-09 07:28
Ok, unfortunately I can only state that it works by disabling Foxygestures and that Mouse Gesture Events isn't affected. Maybe it's an interaction with another configuration of my system, I can't exclude that as long as no one else reports this.

**Comment by marklieberman** [comment] 2017-06-10 23:45
I was able to reproduce this using Nightly, but not Release or Developer edition. It seems to be related to the bug you found. As far as I can tell, there is nothing I can change in Foxy Gestures code. This is probably something in the browser internals.

I recommend that you create an issue on Bugzilla. If you post me the link I will report that I can reproduce the issue. Everything is as you say. It is broken when Foxy Gestures is loaded, but not if the devtools are open.

Steps to reproduce in Nightly are:
4) Make sure devtools are closed.
1) Create a Xenforo demo forum: https://xenforo.com/demo/
2) Login using "admin" for username and password.
3) Create a new topic or reply to a topic. The problem is triggered by the post/reply editor.

The editor seems to be built with https://imperavi.com/redactor/. 

This is the output in my browser console:

![xenforo_error](https://user-images.githubusercontent.com/6473247/27007112-4e4e97ca-4e15-11e7-9f8f-67b069a94387.png)

**Comment by Lurtzae** [comment] 2017-06-10 23:48
Thank you for verifying. Bugzilla ticket can be found here: https://bugzilla.mozilla.org/show_bug.cgi?id=1370463

**Comment by marklieberman** [comment] 2017-06-11 00:03
I think the problem is whatever is producing the error:
```
[Exception... "Must have a non-null string spec or nsIFile object"  nsresult: "0x80070057 (NS_ERROR_ILLEGAL_VALUE)" 
location: "JS frame :: resource://gre/modules/ExtensionParent.jsm :: ProxyContextParent :: line 307"  data: no]
```
This error is appearing on every page load for both Foxy Gestures and smartUp gestures. Since we both have this issue, it suggests to me that Firefox is responsible. I am going to close this issue and follow the Bugzilla issue instead,

**Closed by marklieberman** 2017-06-11 00:03 UTC
