### ISSUE TITLE
User script for "Save Image As"?

### ISSUE THREAD

**Issue by darkj2k** [marklieberman/foxygestures#264] opened 2018-08-03 13:35 UTC
Anyone can show me the script for "Save Image As" for User Scripts of Fire Gestures? Somehow the "Save Media As" gesture don't remember the last saved folder when file path including Japanese characters but "Save Image As" from context menu do not has this issue.

**Comment by marklieberman** [comment] 2018-08-03 14:03
This issue is a dupe of #41. There is no such user script for Save Image As. The context menu item Save Image As is a native Firefox feature and doesn't have the same limitations as web extensions. As a workaround, I recommend making a script similar to [Pattern Matching Quick Save](https://github.com/marklieberman/foxygestures/wiki/User-Scripts#pattern-matching-quick-save) from the user script guide. However, like any web extension it can only save to locations inside Firefox's Download folder.

**Closed by marklieberman** 2018-08-03 14:03 UTC
