### ISSUE TITLE
Add support for there-and-back gestures

### ISSUE THREAD

**Issue by zakius** [marklieberman/foxygestures#22] opened 2017-07-02 20:02 UTC
Like in title: FG fully supported right-left and alike

**Comment by marklieberman** [comment] 2017-07-04 15:04
Duplicate of #17

**Closed by marklieberman** 2017-07-04 15:04 UTC

**Comment by zakius** [comment] 2017-07-04 20:05
moving mouse right then left etc. basically changing direction

**Comment by marklieberman** [comment] 2017-07-04 20:08
I still don't understand. You can bind any command to an LR  or RL gesture movement.

**Comment by zakius** [comment] 2017-07-05 11:35
when I tried to it simply switched to the second movement instead of queuing them, when I moved right-left the final gesture was just left

**Comment by marklieberman** [comment] 2017-07-05 14:04
Are you on OSX or Linux? Where are you trying to do this gesture? In the options or on a page? Can you tell me step by step the buttons and motions you are doing?

**Comment by zakius** [comment] 2017-07-05 15:37
windows, in the "draw gesture to add it" step
press RMB, move right, move left, release RMB
resulting gesture is left

**Comment by marklieberman** [comment] 2017-07-05 15:39
Stay inside the little box where you assign each gesture. Each one a little canvas directive with mouse events bound on it, but if you leave the canvas the gesture is cancelled.

**Comment by zakius** [comment] 2017-07-07 20:53
I can't reproduce the bug now, if I leave the box it indeed cancels gesture completely, but before I experienced only the last line being used if all of them were in the same axis
