### ISSUE TITLE
Scroll to Go to Previous Tab breaks on first tab

### ISSUE THREAD

**Issue by joserebelo** [marklieberman/foxygestures#278] opened 2018-10-03 11:42 UTC
If scroll up or down is bound to "Go to Previous Tab", when used on the first tab (going to the last) wheel gestures stop working altogether. When the mouse is released, the context menu shows up.

Does not happen for the "Go to Next Tab" action.

Unsure if related to #273 and #274.

Firefox 62.0.3 / Windows 10 x64

**Comment by GNQG** [comment] 2018-10-04 14:56
I think it's completely the same issue as my situation(#273) so next release will fix it.

**Comment by marklieberman** [comment] 2018-10-04 16:32
I will make a release this weekend.

Closing as dupe of #273

**Closed by marklieberman** 2018-10-04 16:32 UTC
